const ACTION = {
	BROWSER_API: "BROWSER_API",
	BROWSER_API_TEST: "BROWSER_API_TEST",
	BROWSER_EVENT_ADD: "BROWSER_EVENT_ADD",// client -> server
	BROWSER_EVENT_REMOVE: "BROWSER_EVENT_REMOVE",// client -> server
	BROWSER_EVENT_CLEAR: "BROWSER_EVENT_CLEAR",// client -> server
	BROWSER_EVENT_CALLBACK: "BROWSER_EVENT_CALLBACK",// server -> client
}

export { ACTION };